language: node_js

node_js:
  - '13.8.0'

matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      language: node_js
      node_js: "13.8.0"
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

    - os: linux
      dist: trusty
      sudo: required
      language: node_js
      node_js: "13.8.0"

    - os: windows
      language: node_js
      node_js: "13.8.0"

notifications:
  email: false

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

script:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      npm run electron-pack --linux
    else if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      npm run electron-pack --mac
    else 
      npm run electron-pack --win
    fi

deploy:
  provider: script
  script: npm run electron-pack
  skip_cleanup: true
  on:
    branch: master

branches:
  only:
  - master